version: 0.0
os: linux
files:
  - source: /target/ipms-web.war
    destination: /tmp/codedeploy-deployment-staging-area/
  - source: /scripts/configure_http_port.xsl
    destination: /tmp/codedeploy-deployment-staging-area/
permissions:
  - object: /tmp/codedeploy-deployment-staging-area/
    pattern: "**"
    owner: apache
    group: apache
    mode: 755
    type:
      - file
hooks:
  ApplicationStop:
    - location: scripts/stop_application
      timeout: 300
      runas: root      
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 900 
      runas: root      
  ApplicationStart:
    - location: scripts/write_codedeploy_config.sh
    - location: scripts/start_application
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/basic_health_check.sh
      runas: root
